<?php
/**
* CoTeia's configuration file.
*
* Copyright (C) 2004 Marco Aurélio Graciotto Silva.
* This code is licenced under the GNU General Public License (GPL).
*/

include_once( "compat_hacks.php.inc" );

/**
* Database configuration for CoTeia.
*/
$dbhost = "localhost";
$dbname = "coteia";
$dbuser = "root";
$dbpass = "eimi3a7e";


/**
* Directory where CoTeia's files are installed.
*/
$PATH_COWEB = "/home/magsilva/public_html/Tools/CoTeia";

/**
* URL used to access CoTeia.
*/
$URL_COWEB = "http://www.magsilva.dynalias.net/~magsilva/Tools/CoTeia";

/**
* Information about CoTeia's admin.
*/
$ADMIN = "Marco Aurélio Graciotto Silva";
$ADMIN_EMAIL = "magsilva@icmc.usp.br";
$ADMIN_PASSWORD = $dbpass;

/**
* Path to Java's interpreter.
* Default value: "/usr/lib/java2/bin/java"
*/
$PATH_JAVA = "/usr/lib/java2/bin/java";

/**
* Username that run the CoTeia application (usually the same as the web server).
*
* If running CoTeia within a common user's account, change the defaults
* to "" (blank). Please, use this setting just for testing. CoTeia strives to
* be as secure as possible, but setting $DEFAULT_USER and $DEFAULT_GROUP to
* something different from "" is needed for proper secure operation.
*/
$DEFAULT_USER = "";
$DEFAULT_GROUP = "";

/**
* Default files and directory permissions.
* Default values: 0640 for files, 0750 for directories.
*/
$DEFAULT_FILE_PERMISSION = 0640;
$DEFAULT_DIR_PERMISSION = 0750;

/**
* The Internet URL to access the NoRisk Planning groupware calendar.
*/
$URL_NORISK = "";

/**
* Skin to be used.
* Possible values: default, ffclrp
* Default value: default
*/
$SKIN = "ffclrp";



/****************************************************************************/
/* Parameters that usually doesn't need changes                             */
/****************************************************************************/

/**
* Hack for enabling the use of CoTeia within user's area (useful for testing).
*/
if ( $DEFAULT_USER === "" || $DEFAULT_GROUP === "" ) {
	umask( 0 );
	$DEFAULT_FILE_PERMISSION = 0777;
	$DEFAULT_DIR_PERMISSION = 0777;
}

// Classpath dos bibliotecas para transformação XSLT.
$PATH_XT = $PATH_COWEB . "/libs/xt.jar:" . $PATH_COWEB . "/libs/xp.jar";

/**
* Directory that holds every file created and managed by CoTeia.
* These files are all optional, CoTeia will always run without it (at least
* if the "setup.php" script is run before accessing CoTeia.
*
* This must be a relative directory.
*/
$FILES_DIR = "data";

/**
* Directory with the uploaded files.
*/
$UPLOADS_DIR = $FILES_DIR . "/upload";

/**
* Directory with the (X)HTML pages generated by CoTeia.
*/
$XHTML_DIR = $FILES_DIR . "/themes/" . $SKIN . "/xhtml";

/**
* Directory with the generated XML files.
*/
$XML_DIR = $FILES_DIR . "/xml";

/**
* Image's directory. This is affected by the skin choosen.
* Default value: $FILES_DIR . $SKIN . "/" . "images/"
*/
$IMAGES_DIR = $FILES_DIR . "/themes/" . $SKIN . "/images";

/**
* Directory with the XSLT files that may be used by CoTeia.
*
* The default XSLT filename always is "default.xsl". The directory this
* file is searched for depends upon the skin choosen (for example,
* with "default" skin, the filename will be "$XSL_DIR/default/default.xsl".
*/
$XSL_DIR = $FILES_DIR . "/themes/" . $SKIN . "/xsl";

/**
* Directory with the CSS files that may be used by CoTeia.
*
* The default CSS filename always is "default.xsl". The directory this
* file is searched for depends upon the skin choosen (for example,
* with "default" skin, the filename will be "$CSS_DIR/default/default.css".
*/
$CSS_DIR = $FILES_DIR . "/themes/" . $SKIN . "/css";

/**
* Version. Please, do not change.
*/
$COTEIA_VERSION = "2.0";
